name: Snyk Security Scan
on: push

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated to current version
      
      - name: Run Snyk Scan
        uses: snyk/actions/setup@master  # First set up Snyk CLI
      
      - name: Snyk Test
        uses: snyk/actions/node@v3  # Explicit version
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --all-projects  # Scans all detectable projects
