steps:
  - uses: actions/checkout@v4
  
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.x'

  - name: Generate requirements.txt
    run: |
      pip install pipreqs
      pipreqs . --force
      
  - name: Run Snyk
    run: snyk test --file=requirements.txt
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
