name: Snyk Security Scan
on: push

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Explicit Snyk CLI installation
      - name: Install Snyk CLI
        run: npm install -g snyk
      
      # Run Snyk scan directly
      - name: Run Snyk security scan
        run: snyk test --all-projects --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
