name: Snyk Security Scan for Python Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Scan Python dependencies with Snyk
        run: |
          # Install project dependencies (assuming they're in setup.py or pyproject.toml)
          pip install -e .
          
          # Run Snyk test on installed packages
          snyk test --unmanaged --file=setup.py || echo "Snyk scan completed with findings"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Generate report
        run: |
          snyk test --unmanaged --json-file-output=snyk_report.json || true
          echo "## Snyk Scan Results" >> $GITHUB_STEP_SUMMARY
          jq -r '.vulnerabilities[] | "\(.severity | ascii_upcase): \(.title)\nPackage: \(.packageName)\nAffected versions: \(.version)\nFix: \(.upgradePath[0] // "Not available")\nDetails: \(.url)\n"' snyk_report.json >> $GITHUB_STEP_SUMMARY

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-security-report
          path: snyk_report.json
